spring:
  application:
    name: GoGo
  datasource:
    url: jdbc:postgresql://localhost:5432/car_sharing
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  data:
    web:
      pageable:
        default-page-size: 6
        max-page-size: 15

  mail:
    host: smtp.gmail.com
    port: 587
    username: mauboroda.arturtu@gmail.com
    password: beyp mznc bnkv oied
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gogo-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "carNotification:com.maiboroda.GoGo.dto.CarNotificationDto"

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${EXPIRATION}

gogo:
  settings:
    random-number: 3

app:
  notification:
    emails: mauboroda.arturtu@gmail.com,mentor-email@gmail.com,colleague-email@gmail.com